os: linux
sudo: required
language: python
python:
  - "3.7"

# Change this to your needs
notifications:
  email:
    on_success: change
    on_failure: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - build-essential
    - graphviz
    # packages:
    # MPICH
    - mpich
    - libmpich-dev
    # openmpi
    # - libopenmpi-dev
    # - openmpi-bin

git:
  depth: 3

cache:
  apt: true

before_install:
  # - sudo apt-get install build-essential
  # We need GraphViz to draw figures of graphs and lattices:
  # - sudo apt-get install graphviz
  # - sh ./conf/travis-install-mpi.sh mpich2
  # - mpirun --version

install:
  - pip install -e '.[docs,tests,analytics]'
  - pip install codecov pytest-cov

script:
  - ./run_tests.sh

branches:
  only:
  - master
  - develop

after_success:
  - codecov
