os: linux
sudo: required
language: python
python:
  - "3.7.9"

# Change this to your needs
notifications:
  email:
    on_success: change
    on_failure: always



git:
  depth: 3

cache:
  apt: true

before_install:
  - sudo apt-get install ubuntu-toolchain-r-test -y
  - sudo apt-get install build-essential -y
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install graphviz -y
addons:
  apt:
    update: true

install:
  - pip install -e '.[docs,tests,analytics,balsam]'
  - pip install codecov pytest-cov

script:
  - ./run_tests.sh

branches:
  only:
  - master
  - develop

after_success:
  - codecov
